blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/dsgnr/ShotTrainer/discussions
    about: Ask a question or chat about ShotTrainer with other users.
