[package]
name = "shottrainer-audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
name = "shottrainer_audio"


[dev-dependencies]
proptest.workspace = true
serde_json.workspace = true
testkit = { path = "../testkit" }
